### ISSUE TITLE
{Requests} your config 

### ISSUE THREAD

**Issue by cegi** [cryptolok/ASLRay#2]
I like all your work,advices,and videos so far thanks for sharing, i didn't know how to contact you i don't have social media accounts,would you mind sharing your dotfiles someday ? I saw https://pbs.twimg.com/media/C2OpbVYWQAUx8-t.jpg:large    and i liked it, i too use a window manager.(also what is the cypherpunk cli?)

((If my post is really out of place don't mind it and just delete it of course)) Thanks.

**Comment by cryptolok** [comment]
Thanks for appreciation :)

You can always contact me by email (which is visible on my [git page](https://github.com/cryptolok/)) and my [twitter account](http://twitter.com/cryptolok) is publicly accessible.

By "dotfiles", you mean stuff like .bashrc ? There is nothing fancier than a typical Linux admin would have, with some personalisations of course, but this is what makes my terminal different from the others :) More interesting are perhaps 300+ aliases that I made, but once again, they are personalized for my setup and my tools. However, publication of all this remains possible, although not planified.

Speaking about "window manager", it's just a set of my customized or self-made tools inside [Terminator](https://code.google.com/archive/p/jessies/wikis/Terminator.wiki) (which is more a console than a graphical interface). The "cli" is one of my P2P E2E crypto-chat tools, which uses custom protocol and cipher, perhaps one day it will be released :)

**Comment by cegi** [comment]
another crazy tool heh i'll wait for it.

I understand about aliases, it would only confuses others when using your config, still thanks for answering me. Best config is own config i guess, will work on it.
